# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: demo/v1/demo.proto for package 'Demo.V1'

require 'grpc'
require 'demo/v1/demo_pb'

module Demo
  module V1
    module Demo
      # Demo service: same catalog as REST /graphql — for multi-protocol integration + coverage demos.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'demo.v1.Demo'

        rpc :Health, ::Demo::V1::HealthRequest, ::Demo::V1::HealthReply
        rpc :ListItems, ::Demo::V1::ListItemsRequest, ::Demo::V1::ListItemsReply
        rpc :GetItem, ::Demo::V1::GetItemRequest, ::Demo::V1::GetItemReply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
