# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo/v1/demo.proto

require 'google/protobuf'


descriptor_data = "\n\x12\x64\x65mo/v1/demo.proto\x12\x07\x64\x65mo.v1\"\x0f\n\rHealthRequest\"\x1d\n\x0bHealthReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"/\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04slug\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\"\x12\n\x10ListItemsRequest\".\n\x0eListItemsReply\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\r.demo.v1.Item\"\x1e\n\x0eGetItemRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t\"+\n\x0cGetItemReply\x12\x1b\n\x04item\x18\x01 \x01(\x0b\x32\r.demo.v1.Item2\xba\x01\n\x04\x44\x65mo\x12\x36\n\x06Health\x12\x16.demo.v1.HealthRequest\x1a\x14.demo.v1.HealthReply\x12?\n\tListItems\x12\x19.demo.v1.ListItemsRequest\x1a\x17.demo.v1.ListItemsReply\x12\x39\n\x07GetItem\x12\x17.demo.v1.GetItemRequest\x1a\x15.demo.v1.GetItemReplyB\x0b\xea\x02\x08\x44\x65mo::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Demo
  module V1
    HealthRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.HealthRequest").msgclass
    HealthReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.HealthReply").msgclass
    Item = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.Item").msgclass
    ListItemsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.ListItemsRequest").msgclass
    ListItemsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.ListItemsReply").msgclass
    GetItemRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.GetItemRequest").msgclass
    GetItemReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.GetItemReply").msgclass
  end
end
