name: Trunk

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: trunk-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - uses: trunk-io/trunk-action@v1
